// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SumInput struct {
	Nombre string `json:"nombre"`
	Sum1   int    `json:"sum1"`
	Sum2   int    `json:"sum2"`
	Result int    `json:"result"`
}

type Suma struct {
	ID     int    `json:"id"`
	Nombre string `json:"nombre"`
	Sum1   int    `json:"sum1"`
	Sum2   int    `json:"sum2"`
	Result int    `json:"result"`
}
